<?xml version="1.0"?>
<package format="3">
  <name>turtlebot3_planner</name>
  <version>0.0.1</version>
  <description>TurtleBot3 planner package with RViz integration</description>
  <maintainer email="rahulpanchal7.de@gmail.com">rahulpanchal7</maintainer>
  <license>Apache-2.0</license>

  <!-- Build and exec dependencies -->
  <buildtool_depend>ament_python</buildtool_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>nav_msgs</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>numpy</exec_depend>
  <exec_depend>PyYAML</exec_depend>
  <exec_depend>Pillow</exec_depend>

  <!-- Optional test dependencies -->
  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>
  <test_depend>pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
